import Head from 'next/head'
import Card from '../components/card/Card'
import { Container, Header, Content, Grid, Row, Col } from 'rsuite';
import TuriviusHeader from '../components/layout/Header';

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Turivius Frontend Test | Jóbia Damone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <TuriviusHeader />
      </Header>

      <Container>
        <Content>
          <Grid fluid>
            <Row>
              {props.data.map((card, index) => 
                <Col key={card.title} sm={24}>
                  <Card {...card} index />
                </Col>
              )}
            </Row>
          </Grid>
        </Content>
      </Container>
    </div>
  )
}

Home.getInitialProps = async () => {
  
  const cardApi = await (await fetch('http://localhost:3000/api/cards')).json()
  const entityApi = await (await fetch('http://localhost:3000/api/entities')).json();
  
  /* Aqui eu junto as informações de cadas API. Todas as informações de cards e informações necessárias de entity*/
  const data = cardApi.map(cd => {
    let searchEntity = entityApi.find(en=>en.id==cd.entity); 
    return {...cd, name: searchEntity.name, initials: searchEntity.initials}
  }); 
 
  return {
    data
  }
}